---
title: "West Indies - Scoring by Stadium"
execute:
  echo: false
  message: false
  warning: false
author: "James Brown"
date: "2024-05-30"
format:
  html:
    df-print: default
    theme: cosmo
    self-contained: true
    toc: true
    toc-depth: 3
    fig-width: 8
    fig-height: 6
editor: visual
---

```{r}
# Libraries and functions
library(tidyverse)

# Read in data
international_t20_innings_data <- read_rds("../Data/T20s/Internationals/t20_international_match_innings_data.rds")
cpl_t20_innings_data <- read_rds("../Data/T20s/CPL/cpl_match_innings_data.rds")
```

```{r}
# Combine Data and get all of the venues that are in the 2024 T20 World Cup
internationals <-
  international_t20_innings_data |>
  select(match_date, venue, contains("innings_1")) |>
  filter(
    venue %in% c(
      "Providence Stadium, Guyana",
      "Brian Lara Cricket Academy, Tarouba, Trinidad",
      "Kensington Oval, Bridgetown, Barbados",
      "Sir Vivian Richards Stadium, North Sound, Antigua",
      "Arnos Vale Ground, Kingstown",
      "Daren Sammy National Cricket Stadium, Gros Islet, St Lucia",
      "Central Broward Regional Park Stadium Turf Ground, Lauderhill, Florida"
    )
  )
         
cpl_games <- 
  cpl_t20_innings_data |>
  select(match_date, venue, contains("innings_1")) |>
  filter(
    venue %in% c(
      "Providence Stadium, Guyana",
      "Brian Lara Cricket Academy, Tarouba, Trinidad",
      "Kensington Oval, Bridgetown, Barbados",
      "Sir Vivian Richards Stadium, North Sound, Antigua",
      "Arnos Vale Ground, Kingstown",
      "Daren Sammy National Cricket Stadium, Gros Islet, St Lucia",
      "Central Broward Regional Park Stadium Turf Ground, Lauderhill, Florida"
    )
  )
  
# Combine the data
all_games_wc_venues <-
  bind_rows(internationals, cpl_games) |> 
  # Filter to only games where either 120 balls or more have been bowled, or 10 wickets were taken
  filter(innings_1_balls >= 120 | innings_1_wickets == 10) |> 
  mutate(venue = factor(venue)) |> 
  arrange(venue, match_date) |> 
  group_by(venue) |>
  mutate(match_number = row_number()) |> 
  ungroup()
  
```

```{r}
all_games_wc_venues |> 
  group_by(venue) |>
  summarise(games_played = n(),
            median_innings_1_total = median(innings_1_total),
            mean_innings_1_total = mean(innings_1_total),
            max_innings_1_total = max(innings_1_total)) |> 
  arrange(desc(mean_innings_1_total))

```

```{r}
# Plot First Innings Total by date and venue
all_games_wc_venues |>
  ggplot(aes(x = match_number, y = innings_1_total)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "First Innings Total by date and venue",
       x = "Date",
       y = "First Innings Total") +
  theme_minimal() +
  facet_wrap(~venue)
```

```{r}
# Box Plot comparing first innings totals by venue in descending order
all_games_wc_venues |>
  ggplot(aes(x = fct_reorder(venue, -innings_1_total, .fun = median), y = innings_1_total)) +
  geom_boxplot() +
  labs(title = "First Innings Total by Venue",
       x = "Venue",
       y = "First Innings Total") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

